### ISSUE TITLE
[Feature] Alt Text Generation

### ISSUE THREAD

**Issue by bmachek** [bmachek/lrc-ai-assistant#5]
### Discussed in https://github.com/bmachek/lrc-ai-assistant/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **Scout2022** November 18, 2024</sup>
A great plugin! It would be even better if it could also generate short Alt Text (IPTC accessibility property) for images and write it to the new Alt Text field. It would be convenient to have this functionality integrated directly into one plugin for a simplified workflow. Thanks.</div>

**Comment by bmachek** [comment]
I just checked in the code to main. Please give it a try... :-)

**Comment by Scout2022** [comment]
This works really well for me. A small suggestion: The 'Review Results' windows could indicate what they're showing, e.g. 'Review Results: Alt Text'. Also, the plugin settings could list metadata fields (Caption, Title, Alt Text) in the same order as the 'Review Results' windows appear.

By the way, I've amended the code on my computer to target the 'Headline' metadata field instead of 'Title'. This is because some photo agencies like Getty Images use 'Headline' for the image title in line with the IPTC guidelines (https://www.photometadata.org/META-Resources-Field-Guide-to-Metadata). But metadata standards are used in different ways. Perhaps a checkbox to switch between 'Headline' and 'Title' could be a useful option (as a potential idea for the future).

**Comment by bmachek** [comment]
Thanks for the feedback. I rearranged the order of the checkboxes in the latest commit.
About headline vs title, this is of course doable, but I will address some other features first. Maybe you can open another issue for that, so that it will be addressed in the future.
